application: basingser
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /public/bootstrap/css/bootstrap\.css
  static_files: public/bootstrap/css/bootstrap.css
  upload: public/bootstrap/css/bootstrap\.css

- url: /public/bootstrap/js/bootstrap\.js
  static_files: public/bootstrap/js/bootstrap.js
  upload: public/bootstrap/js/bootstrap\.js

- url: /public/img/korra\.gif
  static_files: public/img/korra.gif
  upload: public/img/korra\.gif

- url: /public/img/text-logo\.png
  static_files: public/img/text-logo.png
  upload: public/img/text-logo\.png

- url: /public/img/welcome\.jpeg
  static_files: public/img/welcome.jpeg
  upload: public/img/welcome\.jpeg

- url: /.*
  script: _go_app
